# Generated by Django 2.2.7 on 2020-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='문제')),
                ('answer_list', models.TextField(verbose_name='답안 리스트')),
                ('answer', models.IntegerField(verbose_name='답')),
            ],
        ),
    ]
