# Generated by Django 2.2.7 on 2020-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '퀴즈 카테고리',
                'verbose_name_plural': '퀴즈 카테고리들',
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '퀴즈', 'verbose_name_plural': '퀴즈들'},
        ),
    ]
