# Generated by Django 2.2.7 on 2020-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbackend', '0003_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='공개'),
        ),
    ]
