# Generated by Django 2.2.7 on 2020-06-26 08:19

from django.db import migrations, models
import django.db.models.deletion
import quizbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizbackend', '0004_category_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('thumbnail', models.ImageField(blank=True, upload_to=quizbackend.models.get_catagory_image_filename, verbose_name='썸네일 이미지')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizbackend.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '결과',
                'verbose_name_plural': '결과들',
            },
        ),
    ]
